version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: houseup-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      MONGO_URI: mongodb://10.1.1.81:27017,10.1.1.82:27017,10.1.1.83:27017/houseup?replicaSet=rs0
      MONGO_DB: houseup
      REDIS_URLS: redis://10.1.1.81:6379/0,redis://10.1.1.82:6379/0,redis://10.1.1.83:6379/0
    ports:
      - "8000:8000"

  mongo-express:
    image: mongo-express
    container_name: houseup-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://10.1.1.81:27017,10.1.1.82:27017,10.1.1.83:27017/houseup?replicaSet=rs0
      ME_CONFIG_BASICAUTH: "false"
    ports:
      - "8081:8081"

  redis-commander-master:
    image: rediscommander/redis-commander:latest
    container_name: houseup-redis-commander-master
    restart: unless-stopped
    environment:
      REDIS_HOSTS: master:10.1.1.81:6379
    ports:
      - "8082:8081"

  redis-commander-replica1:
    image: rediscommander/redis-commander:latest
    container_name: houseup-redis-commander-replica1
    restart: unless-stopped
    environment:
      REDIS_HOSTS: replica1:10.1.1.82:6379
    ports:
      - "8083:8081"

  redis-commander-replica2:
    image: rediscommander/redis-commander:latest
    container_name: houseup-redis-commander-replica2
    restart: unless-stopped
    environment:
      REDIS_HOSTS: replica2:10.1.1.83:6379
    ports:
      - "8084:8081"
